version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nature-remo-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4sk5itkgzwjn"
s3_prefix = "nature-remo-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

